title: Udaya Sankar
description: Computer Science, Programming & Learning In Public
url: "https://uday0214.github.io"
baseurl: ""
lang: en
timezone: Asia/Kolkata
theme: minima

author:
  name: Udaya Sankar

github_username: uday0214
permalink: /blog/:year/:month/:day/:title/

header_pages:
  - blog.md
  - til.md
  - projects.md
  - about.md
